#!/bin/sh
DEFAULT_MUSIC_PLAYER="ncmpcpp"
[ -z "$MUSIC_PLAYER" ] && MUSIC_PLAYER="$DEFAULT_MUSIC_PLAYER" && notify-send -t 2000 "MUSIC_PLAYER env variable not set - using $DEFAULT_MUSIC_PLAYER" || notify-send -t 1000 --urgency=low "Starting Music Player - $MUSIC_PLAYER"
$MUSIC_PLAYER "$@"